[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = ["unreachable", "license", "code-size"]
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 100
tab_width = 2
multiline_func_header = 'params_first'
quote_style = 'single'
wrap_comments = true
# https://book.getfoundry.sh/reference/config/formatter

[profile.integration]
test = 'test/integrations'

[profile.invariant]
test = 'test/invariants'
# This is turned off because we'll need to copy all the validations
# from the code to the tests. While writing tests, we should try to reduce
# the number of reverts and make sure that they are the expected reverts.
# fail_on_revert = true

[profile.gas]
test = 'test/gas'
match-test = 'test_Gas_**'

[profile.alerts]
src = 'src/alerts'
test = 'test/units/alerts'

[profile.pools]
src = 'src/pools'
test = 'test/units/pools'

[profile.rewards]
src = 'src/rewards'
test = 'test/units/rewards'
